version: "3.8"

services:
  mysql:
    restart: always
    image: mysql:latest
    container_name: mysqlDB
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=pw
      - MYSQL_DB=exchange_rate
    ports:
      - 3306:3306
    volumes:
      - .internal/mysqlDB/data:/var/lib/mysqlDB
  adminer:
    image: adminer:latest
    container_name: DB-management
    depends_on:
      - mysql
    ports:
      - 8045:8080
  api:
    depends_on:
      - mysql
    build:
      dockerfile: Dockerfile
    container_name: test-api
    ports:
      - 4057:4057
    environment:
      HTTP_ADDR: ":4057"
      MYSQL_HOST: mysqlDB
      DB_PORT: 3306
    links:
      - mysql


volumes:
  someData:
networks:
  mysql-network: